name: Send Weekly Email

on:
  schedule:
    - cron: '0 6 * * 0' # Every Sunday at 6 AM
  workflow_dispatch: # Allows manual trigger

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::blastula
            any::stringr
            any::dplyr
            any::purrr
            any::readr
            any::httr2
            any::xml2
            any::gt

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send Email
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          set -e
          Rscript -e 'source("personal-weekly-newsletter.R")'

      - name: Save New URLs
        run: |
          set -e
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add scraped_urls.csv || echo "No URLs to add"
          git diff --cached --quiet || git commit -m 'Data updated'
          git push origin || echo "No changes to push"
